server:
  port: 8443
  ssl:
    enabled: true
    key-store-type: PKCS12
    key-store: file:/keystore/edge-test.p12        # ← CORREGIDO (Docker no tiene classpath)
    key-store-password: password
    key-alias: edge-test                           # ← CORREGIDO (tu .p12 usa este alias)
    key-store-type: PKCS12
    trust-store: file:/keystore/edge-test.p12      # ← añadido (Spring Boot 3.4+ lo necesita)
    trust-store-password: password
    trust-store-type: PKCS12

spring.application.name: gateway
spring:
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        # ======================
        # MS-NOTIFICATION
        # ======================
        - id: ms-notification
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/**
          filters:
            - StripPrefix=1

        # OpenAPI JSON con prefijo /openapi/ms-notification/...
        - id: ms-notification-openapi-docs-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-notification/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        # Swagger UI con prefijo /openapi/ms-notification/swagger-ui/**
        - id: ms-notification-swagger-static-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-notification/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        # ======================
        # MS-REGISTRATION (ejemplo para agregar otros microservicios: copia esta sección y cambia el nombre/id/uri/path)
        # ======================
        - id: ms-registration
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/**
          filters:
            - StripPrefix=1

        # Swagger UI con prefijo /openapi/ms-registration/swagger-ui/** (ejemplo para agregar Swagger/OpenAPI a otros microservicios: copia y cambia el nombre/path)
        - id: ms-registration-swagger-static-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-registration/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        # OpenAPI JSON con prefijo /openapi/ms-registration/... (ejemplo para agregar OpenAPI a otros microservicios: copia y cambia el nombre/path)
        - id: ms-registration-openapi-docs-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-registration/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        # ======================
        # EUREKA WEB (ejemplo para agregar rutas a Eureka u otros servicios internos)
        # ======================
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        # ======================
        # CONFIG SERVER (ejemplo para agregar ruta al config server, si necesitas exponerlo)
        # ======================
        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*),/$\{segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ucb.edu.bo:8081/realms/DemoUCB   # ← adaptado a tu puerto 8081

management.endpoint.gateway.enabled: true
management.endpoint.health.show-details: "ALWAYS"
management.endpoints.web.exposure.include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE