server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/keystore/edge-test.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: edge-test
    key-password: password
    trust-store: file:/keystore/edge-test.p12
    trust-store-password: password
    trust-store-type: PKCS12

spring:
  application:
    name: gateway
  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:
        # ======================
        # MS-REGISTRATION
        # ======================
        - id: ms-registration
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/**
          filters:
            - StripPrefix=1

        # Ruta específica para Swagger UI principal de MS-Registration
        - id: ms-registration-swagger-ui-main
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/swagger-ui.html
          filters:
            - RewritePath=/ms-registration/swagger-ui.html, /swagger-ui.html

        # Documento OpenAPI para MS-Registration (requerido para que Swagger UI cargue correctamente)
        - id: ms-registration-openapi-docs
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/v3/api-docs/**
          filters:
            - RewritePath=/ms-registration/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

        # Recursos estáticos de Swagger UI para MS-Registration
        - id: ms-registration-swagger-static
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/swagger-ui/**
          filters:
            - RewritePath=/ms-registration/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        # ======================
        # MS-NOTIFICATION
        # ======================
        - id: ms-notification
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/**
          filters:
            - StripPrefix=1

        # Ruta específica para Swagger UI principal de MS-Notification
        - id: ms-notification-swagger-ui-main
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/swagger-ui.html
          filters:
            - RewritePath=/ms-notification/swagger-ui.html, /swagger-ui.html

        # Documento OpenAPI para MS-Notification (requerido para que Swagger UI cargue correctamente)
        - id: ms-notification-openapi-docs
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/v3/api-docs/**
          filters:
            - RewritePath=/ms-notification/v3/api-docs(?<segment>.*), /v3/api-docs${segment}

        # Recursos estáticos de Swagger UI para MS-Notification
        - id: ms-notification-swagger-static
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/swagger-ui/**
          filters:
            - RewritePath=/ms-notification/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        # ======================
        # Rutas adicionales para compatibilidad con rutas prefijadas existentes
        # ======================
        - id: ms-registration-openapi-docs-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-registration/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: ms-registration-swagger-static-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-registration/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        - id: ms-notification-openapi-docs-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-notification/v3/api-docs(?<segment>/?.*), /v3/api-docs${segment}

        - id: ms-notification-swagger-static-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-notification/swagger-ui/(?<segment>.*), /swagger-ui/${segment}

        # ======================
        # EUREKA
        # ======================
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        # ======================
        # CONFIG SERVER
        # ======================
        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /{segment}

management:
  endpoint:
    gateway:
      enabled: true
    health:
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE