server:
  port: 8443
  ssl:
    enabled: true
    key-store: file:/keystore/edge-test.p12
    key-store-password: password
    key-store-type: PKCS12
    key-alias: edge-test
    key-password: password
    trust-store: file:/keystore/edge-test.p12
    trust-store-password: password
    trust-store-type: PKCS12

spring:
  application:
    name: gateway

  cloud:
    gateway:

      # 🚫 DESACTIVAR totalmente CORS interno del Gateway
      globalcors:
        add-to-simple-url-handler-mapping: false
        corsConfigurations: {}

      default-filters:
        - TokenRelay

      routes:

        # ======================
        # MS-NOTIFICATION
        # ======================
        - id: ms-notification
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/**
          filters:
            - StripPrefix=1

        - id: ms-notification-openapi-docs-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-notification/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        - id: ms-notification-swagger-static-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-notification/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        # ======================
        # MS-REGISTRATION
        # ======================
        - id: ms-registration
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/**
          filters:
            - StripPrefix=1

        - id: ms-registration-swagger-static-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-registration/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        - id: ms-registration-openapi-docs-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-registration/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}
            
        # ======================
        # MS-BOOK
        # ======================
        - id: ms-book
          uri: lb://MS-BOOK
          predicates:
            - Path=/ms-book/**
          filters:
            - StripPrefix=1

        - id: ms-book-openapi-docs-prefixed
          uri: lb://MS-BOOK
          predicates:
            - Path=/openapi/ms-book/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-book/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        - id: ms-book-swagger-static-prefixed
          uri: lb://MS-BOOK
          predicates:
            - Path=/openapi/ms-book/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-book/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        # ======================
        # MS-LOAN
        # ======================
        - id: ms-loan
          uri: lb://MS-LOAN
          predicates:
            - Path=/ms-loan/**
          filters:
            - StripPrefix=1

        - id: ms-loan-openapi-docs-prefixed
          uri: lb://MS-LOAN
          predicates:
            - Path=/openapi/ms-loan/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-loan/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        - id: ms-loan-swagger-static-prefixed
          uri: lb://MS-LOAN
          predicates:
            - Path=/openapi/ms-loan/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-loan/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        # ======================
        # EUREKA WEB
        # ======================
        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        # ======================
        # CONFIG SERVER
        # ======================
        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*),/${segment}

  security:
    oauth2:
      client:
        provider:
          keycloak:
            issuer-uri: http://keycloak.ucb.edu.bo:8081/realms/DemoUCB
            user-name-attribute: preferred_username
        registration:
          gateway-client:
            provider: keycloak
            client-id: angular-app
            client-secret: no-secret-needed  # Keycloak público
            authorization-grant-type: authorization_code
            scope: openid,profile,email
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ucb.edu.bo:8081/realms/DemoUCB

management:
  endpoint:
    gateway:
      enabled: true
    health:
      healthcheckMicroservices:
        enabled: false
      show-details: ALWAYS
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
