server:
  port: 8443
  ssl:
    key-store-type: PKCS12
    key-store: classpath:keystore/edge.p12
    key-store-password: password
    key-alias: localhost

app:
  eureka-server: localhost

spring:
  application:
    name: gateway

  cloud:
    gateway:
      default-filters:
        - TokenRelay
      routes:

        - id: ms-notification
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/ms-notification/**
          filters:
            - StripPrefix=1

        - id: ms-notification-openapi-docs-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-notification/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        - id: ms-notification-swagger-static-prefixed
          uri: lb://MS-NOTIFICATION
          predicates:
            - Path=/openapi/ms-notification/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-notification/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        - id: ms-registration
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/ms-registration/**
          filters:
            - StripPrefix=1

        - id: ms-registration-swagger-static-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/swagger-ui/**
          filters:
            - RewritePath=/openapi/ms-registration/swagger-ui/(?<segment>.*), /openapi/swagger-ui/${segment}

        - id: ms-registration-openapi-docs-prefixed
          uri: lb://MS-REGISTRATION
          predicates:
            - Path=/openapi/ms-registration/v3/api-docs/**
          filters:
            - RewritePath=/openapi/ms-registration/v3/api-docs(?<segment>/?.*), /openapi/v3/api-docs${segment}

        - id: eureka-web-start
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/web
          filters:
            - SetPath=/

        - id: eureka-web-other
          uri: http://${app.eureka-server}:8761
          predicates:
            - Path=/eureka/**

        - id: config-server
          uri: ${spring.cloud.config.uri}
          predicates:
            - Path=/config/**
          filters:
            - RewritePath=/config/(?<segment>.*), /${segment}

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak.ucb.edu.bo:8081/realms/DemoUCB

management:
  endpoint:
    gateway:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
